### ISSUE TITLE
Performance: avoid DB writes during plugin boot

### ISSUE THREAD

**Issue by lkraav** [ilGhera/jw-player-7-for-wp#2]
https://github.com/ilGhera/jw-player-7-for-wp/blob/free-2.0.1/jw-player-7-for-wp.php#L34

We should certainly not be calling `update_option()` during plugin boot with what looks to be a 99.99% static value on every single request here.

Your thoughts?

**Comment by ilGhera** [comment]
You're right, this is not a good way to do that, I need to find a better solution.
Thanks for reporting this.

**Comment by lkraav** [comment]
Good to know. What's your timeline for working on this plugin? Last commits are from 6 months ago. Maybe I'll fork it and start filing PR-s to move faster.

**Comment by ilGhera** [comment]
Hi,
I'm focused on several other projects but I'll do my best.
Thanks ;-)
